// Akatsi Market Portal - Local Seed Data

const MARKET_CONFIG = {
  // Reference market day: July 1, 2026 (Wednesday)
  // 4-day cycle. Next market days will be: July 5 (Sunday), July 9 (Thursday), etc.
  referenceMarketDay: "2026-07-01T06:00:00Z", 
  cycleDays: 4,
};

const COMMODITIES = [
  {
    id: "yam",
    name: "White Yam (Tuber)",
    category: "Tubers",
    price: 35.00,
    prevPrice: 32.50,
    unit: "Medium Tuber",
    change: 7.7,
    trend: [28, 30, 32.5, 31, 32.5, 35],
    inStock: true,
    description: "Premium Volta Region yams. Dry, starchy, and perfect for boiling or pounding."
  },
  {
    id: "cassava",
    name: "Cassava (Bag)",
    category: "Tubers",
    price: 280.00,
    prevPrice: 295.00,
    unit: "50kg Bag",
    change: -5.1,
    trend: [310, 305, 300, 295, 290, 280],
    inStock: true,
    description: "Freshly harvested cassava roots. Ideal for gari, fufu, and cassava flour processing."
  },
  {
    id: "maize",
    name: "White Maize",
    category: "Grains",
    price: 18.00,
    prevPrice: 17.50,
    unit: "Olonka (approx 2.5kg)",
    change: 2.8,
    trend: [15.5, 16.0, 16.5, 17.0, 17.5, 18.0],
    inStock: true,
    description: "Well-dried local white corn, perfect for banku, kenkey, or poultry feed."
  },
  {
    id: "tomatoes",
    name: "Local Tomatoes",
    category: "Vegetables",
    price: 120.00,
    prevPrice: 110.00,
    unit: "Medium Paint Bucket",
    change: 9.1,
    trend: [90, 100, 115, 105, 110, 120],
    inStock: true,
    description: "Freshly plucked farm tomatoes from Akatsi North irrigation farms."
  },
  {
    id: "shallots",
    name: "Akatsi Red Shallots",
    category: "Vegetables",
    price: 45.00,
    prevPrice: 45.00,
    unit: "Olonka",
    change: 0.0,
    trend: [40, 42, 45, 45, 45, 45],
    inStock: true,
    description: "World-renowned Akatsi shallots, highly aromatic and full of flavor."
  },
  {
    id: "plantain",
    name: "Apem Plantain",
    category: "Fruits & Vegetables",
    price: 55.00,
    prevPrice: 60.00,
    unit: "Large Bunch",
    change: -8.3,
    trend: [65, 68, 62, 60, 60, 55],
    inStock: true,
    description: "Green and ripe plantain bunches, excellent for local dishes like Kelewele and Ampesi."
  },
  {
    id: "goat",
    name: "Local Volta Goat",
    category: "Livestock",
    price: 850.00,
    prevPrice: 800.00,
    unit: "Medium Size",
    change: 6.2,
    trend: [750, 780, 800, 790, 800, 850],
    inStock: true,
    description: "Healthy, pasture-fed local goats. Highly sought after for festive occasions."
  },
  {
    id: "poultry",
    name: "Local Fowl",
    category: "Livestock",
    price: 110.00,
    prevPrice: 115.00,
    unit: "Per Bird",
    change: -4.3,
    trend: [105, 110, 120, 115, 115, 110],
    inStock: true,
    description: "Free-range local chickens (roosters and layers), firm meat and rich flavor."
  },
  {
    id: "earthenware",
    name: "Local Earthenware Pot (Wegba / Asanka)",
    category: "Crafts & Tools",
    price: 25.00,
    prevPrice: 22.00,
    unit: "Medium Pot",
    change: 13.6,
    trend: [20, 20, 22, 22, 22, 25],
    inStock: true,
    description: "Handcrafted clay pots/bowls for grinding (Wegba / Asanka) or slow-cooking traditional soups."
  },
  {
    id: "basketry",
    name: "Handwoven Cane Basket (Keve)",
    category: "Crafts & Tools",
    price: 30.00,
    prevPrice: 30.00,
    unit: "One Piece",
    change: 0.0,
    trend: [28, 28, 30, 30, 30, 30],
    inStock: true,
    description: "Strong, durable Ewe handwoven storage and shopping baskets made from local cane."
  },
  {
    id: "farmtools",
    name: "Local Farming Hoe & Cutlass",
    category: "Crafts & Tools",
    price: 65.00,
    prevPrice: 60.00,
    unit: "Set (1 Hoe, 1 Cutlass)",
    change: 8.3,
    trend: [55, 58, 60, 60, 60, 65],
    inStock: true,
    description: "Forged metal farm implements with sturdy wooden handles. Perfect for weeding and land preparation."
  },
  {
    id: "calabash",
    name: "Traditional Calabash (Trese)",
    category: "Crafts & Tools",
    price: 12.00,
    prevPrice: 10.00,
    unit: "One Piece (Medium / Large)",
    change: 20.0,
    trend: [8, 8, 10, 10, 10, 12],
    inStock: true,
    description: "Dried and hollowed-out gourds used traditionally for drinking water, palm wine (Liha), or as decorative bowls."
  },
  {
    id: "thriftclothing",
    name: "Second Hand Clothing & Footwear",
    category: "Clothing",
    price: 45.00,
    prevPrice: 50.00,
    unit: "Selection (1 Shirt & Pants / Pair of Thrift Shoes)",
    change: -10.0,
    trend: [55, 55, 52, 50, 50, 45],
    inStock: true,
    description: "Affordable selection of imported thrift clothing (jeans, shirts) and clean footwear."
  },
  {
    id: "localsnacks",
    name: "Agbelikaklo & Atsifuifui Snacks",
    category: "Prepared Food",
    price: 5.00,
    prevPrice: 4.50,
    unit: "Portion (5 pcs)",
    change: 11.1,
    trend: [4.0, 4.0, 4.5, 4.5, 4.5, 5.0],
    inStock: true,
    description: "Crunchy local fried cassava balls (Agbelikaklo) and Atsifuifui (traditional Ewe snack) served hot."
  },
  {
    id: "charcoal",
    name: "Local Hardwood Charcoal",
    category: "Crafts & Tools",
    price: 90.00,
    prevPrice: 85.00,
    unit: "Large Bag",
    change: 5.9,
    trend: [80, 80, 85, 85, 85, 90],
    inStock: true,
    description: "Premium quality charcoal burned from dry hardwoods. Burns clean with high heat."
  }
];

const VENDORS = [
  {
    id: 1,
    name: "Mama Beatrice Agribusiness",
    stall: "Zone A, Stall 14",
    zone: "agriculture",
    category: "Tubers",
    rating: 4.9,
    verified: true,
    phone: "+233 24 123 4567",
    products: ["Yam", "Cassava", "Sweet Potato"],
    bio: "Supplying top-grade yams and tubers directly from local Volta farms to wholesale buyers for over 15 years."
  },
  {
    id: 2,
    name: "Torgbui Gbedegble Livestock",
    stall: "Zone C (Livestock Yard), Stall 05",
    zone: "livestock",
    category: "Livestock",
    rating: 4.7,
    verified: true,
    phone: "+233 55 987 6543",
    products: ["Goat", "Sheep", "Local Fowl"],
    bio: "Your trusted dealer in healthy livestock. We offer vaccination checks and transport arrangements for bulk orders."
  },
  {
    id: 3,
    name: "Dzifa Shallot Empire",
    stall: "Zone A, Stall 42",
    zone: "agriculture",
    category: "Vegetables",
    rating: 4.8,
    verified: true,
    phone: "+233 27 445 5566",
    products: ["Akatsi Red Shallots", "Garlic", "Ginger"],
    bio: "Export-grade red shallots grown in the rich soils of Keta and Akatsi basins. Cleaned, dried, and packed."
  },
  {
    id: 4,
    name: "Koforidua Textiles & Kente",
    stall: "Zone B (Apparel), Stall 28",
    zone: "clothing",
    category: "Clothing",
    rating: 4.6,
    verified: false,
    phone: "+233 20 112 2334",
    products: ["Handwoven Kente", "Wax Prints", "Lace Fabrics"],
    bio: "Beautiful authentic Ewe and Asante Kente cloths. Customized designs available on order."
  },
  {
    id: 5,
    name: "Sister Mawusi Food Joint",
    stall: "Zone D (Food Court), Stall 02",
    zone: "food",
    category: "Prepared Food",
    rating: 5.0,
    verified: true,
    phone: "+233 24 999 8877",
    products: ["Akple with Fetridetsi", "Banku with Tilapia", "Liha Drink"],
    bio: "Hot, freshly prepared traditional Ewe dishes. Try our signature okra soup (Fetridetsi) with hot Akple!"
  },
  {
    id: 6,
    name: "Agbeli Farms & Gari Processing",
    stall: "Zone A, Stall 19",
    zone: "agriculture",
    category: "Tubers",
    rating: 4.5,
    verified: false,
    phone: "+233 24 333 2211",
    products: ["Gari (Fine & Medium)", "Tapioca", "Starch"],
    bio: "Direct processors of high-quality crunchy white and yellow gari. Sold in paint buckets and bags."
  },
  {
    id: 7,
    name: "Akatsi Blacksmith & Farm Tools Shop",
    stall: "Zone A, Stall 85",
    zone: "agriculture",
    category: "Crafts & Tools",
    rating: 4.8,
    verified: true,
    phone: "+233 24 444 5555",
    products: ["Local Farming Hoe & Cutlass", "Spade", "Rake"],
    bio: "Quality locally forged farming hoes, cutlasses, and tools crafted by generations of Ewe metal smiths."
  },
  {
    id: 8,
    name: "Keta Clay Crafts & Weavers",
    stall: "Zone B, Stall 67",
    zone: "clothing",
    category: "Crafts & Tools",
    rating: 4.7,
    verified: true,
    phone: "+233 20 888 7777",
    products: ["Local Earthenware Pot (Wegba / Asanka)", "Handwoven Cane Basket (Keve)", "Traditional Calabash (Trese)"],
    bio: "Authentic local earthenware grinding bowls (Wegba / Asanka), cooking pots, and beautifully handwoven shopping/cane baskets."
  },
  {
    id: 9,
    name: "Afevi Charcoal Depo",
    stall: "Zone C, Stall 90",
    zone: "livestock",
    category: "Crafts & Tools",
    rating: 4.6,
    verified: false,
    phone: "+233 54 333 4444",
    products: ["Local Hardwood Charcoal", "Firewood"],
    bio: "Wholesale and retail hardwood charcoal bags. Sourced sustainably from local woodlots."
  }
];

const TRANSPORT_ROUTES = [
  {
    from: "Accra (Tudu Station / Tema Station / Madina)",
    to: "Akatsi / Abor Lorry Park",
    type: "Trotro / Sprinter / Bus",
    fare: "GH₵ 55.00",
    frequency: "Every 30 mins (Market days), Hourly (Regular days)",
    duration: "Approx. 2.5 - 3 hours"
  },
  {
    from: "Ho (Central Lorry Park)",
    to: "Akatsi Lorry Park",
    type: "Shared Taxi / Trotro",
    fare: "GH₵ 40.00",
    frequency: "Regular departures",
    duration: "Approx. 1.5 hours"
  },
  {
    from: "Aflao (Border)",
    to: "Akatsi Lorry Park",
    type: "Trotro / Shared Taxi",
    fare: "GH₵ 35.00",
    frequency: "Regular departures",
    duration: "Approx. 1 hour"
  }
];

const NEWS = [
  {
    id: 1,
    title: "Akatsi 24-Hour Market Expansion Project Underway",
    date: "July 2, 2026",
    summary: "Local government begins installation of new LED solar streetlights and security booths to support overnight trading activities.",
    readTime: "2 min read"
  },
  {
    id: 2,
    title: "Shallot Farm Irrigation Support Scheme",
    date: "June 28, 2026",
    summary: "Ministry of Agriculture supplies motorized pumps and hoses to farmers in Akatsi South to secure production during dry patches.",
    readTime: "3 min read"
  }
];

const TRANSLATIONS = {
  en: {
    title: "Akatsi Market Portal",
    tagline: "Volta's Commercial Heartbeat",
    liveIndicator: "LIVE MARKET UPDATE",
    schedule: "Schedule",
    prices: "Prices",
    map: "Map",
    directory: "Directory",
    guide: "Guide",
    statusBoxTitle: "Market Day Status",
    welcome: "Welcome to Akatsi, Ghana",
    subWelcome: "Explore Volta’s Largest Four-Day Hub",
    welcomeText: "Connecting farmers, wholesalers, and retail buyers. Track live commodity prices, locate trusted local vendors, and plan your next trading visit with ease.",
    countdownSubtitle: "COUNTDOWN TO MAJOR MARKET DAY",
    countdownFooter: "Akatsi operates on a recurring 4-day cycle. Traders arrive from all parts of West Africa.",
    activeToday: "ACTIVE TODAY",
    standby: "STANDBY",
    activeStatus: "🎉 TODAY IS MARKET DAY! The market is vibrant and active right now.",
    standbyStatus: "Standby mode. Regular trading is ongoing at a relaxed pace.",
    days: "Days",
    hours: "Hours",
    minutes: "Mins",
    seconds: "Secs",
    
    priceTitleBadge: "RETAIL & WHOLESALE",
    priceTitle: "Commodity Price Index",
    priceDesc: "Monitored prices of staple farm produce and livestock in Akatsi. Updated on market days.",
    allCategories: "All Items",
    tubers: "Tubers",
    grains: "Grains",
    veg: "Vegetables & Fruits",
    livestock: "Livestock",
    clothing: "Clothing & Apparel",
    food: "Prepared Food",
    craftsTools: "Crafts & Tools",
    
    unit: "Unit",
    latestPrice: "Latest Price",
    changeLabel: "Change (4 Days)",
    baseUnitLabel: "Base Unit",
    priceTrendLabel: "Price Trend (Last 30 Days)",
    daysAgo: "30 days ago",
    latest: "Latest",
    
    mapTitleBadge: "INTERACTIVE GUIDE",
    mapTitle: "Market Quadrant Map",
    mapDesc: "Hover over the quadrants to inspect sections. Click on a zone to view lists of vendors located there.",
    mapInfoTitle: "Select a Quadrant",
    mapInfoDesc: "Hover over any region on the map to inspect its general merchandise, accessibility, and active stalls.",
    mapHighlightProduce: "Major Produce:",
    mapHighlightAccess: "Accessibility:",
    mapHighlightCount: "Stall Count:",
    mapFilterBtn: "Filter Directory for this Zone",
    
    dirTitleBadge: "REGISTERED STALLS",
    dirTitle: "Stall & Vendor Directory",
    dirDesc: "Search and get in touch with wholesalers and retailers. View ratings and verify stall details.",
    dirSearchPlaceholder: "Search by vendor name, stall, or product...",
    dirCategoryLabel: "Category:",
    dirZoneLabel: "Zone:",
    dirResetBtn: "Reset",
    dirVerified: "VERIFIED",
    dirContactCall: "Phone / Call",
    dirInquireBtn: "Inquire",
    dirInquireTitle: "Contact Vendor",
    dirInquirePlaceholder: "Type your inquiry or message here...",
    dirSendBtn: "Send Message",
    dirCancelBtn: "Cancel",
    
    showingCount: "Showing {count} of {total} registered stalls",
    noVendors: "No vendors found matching your current filter settings.",
    
    transportTitle: "Transport & Connectivity",
    transportDesc: "Akatsi is strategically located at the intersection of routes leading to Accra, Ho, and Aflao (Togo border).",
    thRoute: "Route",
    thType: "Type",
    thFreq: "Frequency",
    thFare: "Est. Fare",
    
    newsTitle: "Community News & Projects",
    spotlightTitle: "Project Spotlight: The 24-Hour Market Initiative",
    spotlightDesc: "Akatsi is transforming into a 24-hour trading hub. To facilitate this, the local assembly has commissioned modern security outposts and lighting infrastructure to ensure high safety standards for late-night traders.",
    histTitle: "History & Heritage",
    histBody1: "Akatsi was founded by the great hunter Adela Letsa Korba I in the 16th century, whose ancestors hailed from Anloga.",
    histBody2: "The market land was acquired from the Letsa Korba Family, who are the traditional Overlords of Akatsi.",
    ctaBadge: "Investment & Growth",
    ctaTitle: "Come Invest and Grow Your Business",
    ctaDesc: "Akatsi is one of the fastest-developing municipalities in Ghana, offering immense investment and business potentials. Partner with Volta's commercial gateway today—you will never regret investing in Akatsi."
  },
  ee: {
    title: "Akatsi Asime",
    tagline: "Volta Ƒe Asitsagã Kpe",
    liveIndicator: "ASIME NYAWO KATÃ",
    schedule: "Ðoɖowó",
    prices: "Asiaswo",
    map: "Anyigbatata",
    directory: "Asitsaláwo",
    guide: "Mɔfiame",
    statusBoxTitle: "Asigbe Ƒe Nɔnɔme",
    welcome: "Woezɔ yi Akatsi, Ghana",
    subWelcome: "Yi Volta Ƒe Asigã Si Woɖona Ŋkeke Ene Ðesiaɖe Me",
    welcomeText: "Ebla agbledelawo, asitsagãwo, kple asitsagã sue dzralawo ƒo. Kpɔ nudzradzrawo ƒe asiaswo kpɔ, dze asitsala siwo ŋu kakaɖedzi le egbɔ, eye nàɖo egbegbe asiyiyi ɖoɖowo bɔbɔe.",
    countdownSubtitle: "ŊKEKE SIWO TSI KPOÐO ÐE ASIGÃ GÃ LA ŊU",
    countdownFooter: "Akatsi asime zɔna ɖe ŋkeke 4 ƒe totrɔ ɖoɖo dzi. Asitsalawo tsoa Ɣetoɖoƒe Afrika katã vana.",
    activeToday: "ASIME LE EDZI EGBE",
    standby: "ASIME METRƆ O",
    activeStatus: "🎉 EGBEE NYE ASIGBE! Asime la le edzi vevie fifia.",
    standbyStatus: "Asime metrɔ o. Asitsatsa le edzi bɔbɔe maɖetsitsi.",
    days: "Ŋkeke",
    hours: "Gaƒoƒo",
    minutes: "Miniti",
    seconds: "Sekend",
    
    priceTitleBadge: "ASISUE KPLE WHOLESALE",
    priceTitle: "Nudzradzrawo Ƒe Asiaswo Kpɔƒe",
    priceDesc: "Agblemenuku kple lãwo ƒe asiaswo siwo ŋu wole ŋku lém le Akatsi. Wotrɔnae le asigbewo dzi.",
    allCategories: "Nuwó Katã",
    tubers: "Nu-ɖeɖewo",
    grains: "Ku-nukuwo",
    veg: "Agbledede & Kutsetsewo",
    livestock: "Agbelãwo",
    clothing: "Avɔwo & Kente",
    food: "Nuɖuɖu Ðadzewo",
    craftsTools: "Asinudɔwɔwɔwo & Dɔwɔnuwo",
    
    unit: "Kpe",
    latestPrice: "Asia Fifia",
    changeLabel: "Asia Totrɔ (Ŋkeke 4)",
    baseUnitLabel: "Kpe Gɔme",
    priceTrendLabel: "Asia Totrɔ Totrɔ (Ŋkeke 30 Siwo Vayi)",
    daysAgo: "Ŋkeke 30 siwo vayi",
    latest: "Fifia tɔ",
    
    mapTitleBadge: "MƆFIAME KPE",
    mapTitle: "Asime Akpa Vovovowo Ƒe Anyigbatata",
    mapDesc: "Fia asime ƒe akpa vovovowo kple wò mɔfiame tẽ. Zi akpa aɖe dzi nàkpɔ asitsala siwo le afima.",
    mapInfoTitle: "Tia Akpa Aɖe",
    mapInfoDesc: "Kplɔ wò mouse yi akpa aɖe dzi le anyigbatata la dzi be nàkpɔ nudzrawo, mɔnukpɔkpɔwo, kple asikpe siwo le afima.",
    mapHighlightProduce: "Nudzradzra Gãwo:",
    mapHighlightAccess: "Mɔkpɔkpɔ:",
    mapHighlightCount: "Asikpe Xexlẽme:",
    mapFilterBtn: "Tia Asitsalawo Le Akpa Sia",
    
    dirTitleBadge: "ASIKPE SIWO WOTA",
    dirTitle: "Asitsalawo Kple Asikpe Xexlẽme",
    dirDesc: "Didi eye nàdo ƒome kple asitsagãwo kple asikpe sue asitsalawo. Kpɔ wò rating kple stall nyawo kakaɖedzi.",
    dirSearchPlaceholder: "Didi asitsalã, asikpe, loo nudzra...",
    dirCategoryLabel: "Hatsoɖo:",
    dirZoneLabel: "Akpa:",
    dirResetBtn: "Gbugbɔɖo",
    dirVerified: "KAKAÐEDZI LE EŊU",
    dirContactCall: "Ka Ka / Ka Mɔ",
    dirInquireBtn: "Inquire",
    dirInquireTitle: "Gblɔ Nya Na Asitsala",
    dirInquirePlaceholder: "Gblɔ wò nya alo biabia le afi...",
    dirSendBtn: "Ðo Nya Ða",
    dirCancelBtn: "Gbe",
    
    showingCount: "Wole asitsala {count} fiam tso {total} me",
    noVendors: "Womekpɔ asitsala aɖeke si sɔ kple wò didi o.",
    
    transportTitle: "Dɔdodo & Transit",
    transportDesc: "Akatsi le nɔƒe gã aɖe le mɔ siwo yi Accra, Ho, kple Aflao (Togo liƒo) dome.",
    thRoute: "Mɔ",
    thType: "Trom",
    thFreq: "Kakáɖe",
    thFare: "Asia",
    
    newsTitle: "Kɔmifiame Nyawo & Dɔwɔwɔwo",
    spotlightTitle: "Dɔwɔwɔ Ŋu Ŋkuɖoɖo: Gaƒoƒo 24 Asitsatsa Mɔɖoɖo",
    spotlightDesc: "Akatsi le trɔtrɔm be wòazu zã kple keli asitsagã. Be wòasɔ la, dua ƒe dziɖuɖua ɖo dedienɔnɔ kple keli geɖe be zã me asitsalawo nanɔ dedie.",
    histTitle: "Akatsi Nutinya & Kɔnuwo",
    histBody1: "Adela Letsa Korba I si nye adela gã aɖe si tso Anloga, ye ɖo Akatsi du la anyi le ƒe alafa 16lia me.",
    histBody2: "Letsa Korba ƒomea, siwo nye Akatsi nuto Overlord gãwo la ƒe anyigba dzie woɖo asigbe la ɖo.",
    ctaBadge: "Gadzraɖoƒe & Tsitsim",
    ctaTitle: "Va Gadzraɖo eye nàdzi wò Dɔwɔƒe ɖe edzi",
    ctaDesc: "Akatsi nye dua siwo le tsitsim kaba nuto le Ghana eye asitsamɔnu kple gadzraɖomɔnu geɖewo le afi. Mabu nu o ne èɖo adzɔnu/gadzraɖo anyi le Akatsi. Va asime eye nànyo wò dɔwɔwɔ ɖe edzi."
  }
};

